### ISSUE TITLE
Feature: l-control-layers @change event needed 

### ISSUE THREAD

**Issue by alexey2baranov** [vue-leaflet/Vue2Leaflet#503]
Hello! 

We didn't find l-control-layers @change event in specs. It is very important event if you want to save UI state between sessions.

Thanks!

**Comment by DonNicoJs** [comment]
@alexey2baranov Hi thanks for the question! This is because `leaflet` does not emit any event on the control when a layer is changed, they are emitted on the map, in turn with `vue2leaflet` you can listen to them with:

`<l-map @baselayerchange="doSeomthing" ...>`

full list of events => 
https://leafletjs.com/reference-1.6.0.html#map-event
