### ISSUE TITLE
Color of the map not changing when updating the prop value

### ISSUE THREAD

**Issue by romain130492** [vue-leaflet/Vue2Leaflet#605]
Hello !

Firstly thanks for this repository !
* I have a list of variables, i would like the map to  update according to the variable target I click on.
* I'm updating the prop `value` of the `l-choropleth-layer` component.
* Eg : ``` const obj = {
        key: "variableA"
        metric:"variableA"
      };  ```

* **When I update the `variable`, the colors of the map are not updated according to the new values.**
  * But when I hover the map i can see that the percent of the departement are also updated.
  * So i can deduct that everything seem to have been updated except the colors, may I know if there is an option to pass as a prop to force the map colors to be also `reactive` or something ? 

Thanks !

**Comment by mikeu** [comment]
Hi @romain130492 , are you still facing this issue? It's hard to say without an example to look at, but it sounds to me at first glance as if this is more related to the [vue-choropleth](https://github.com/voluntadpear/vue-choropleth) plugin component than Vue2Leaflet itself.

If you're still having trouble with this and think that the problem is with this library, then if you put together a minimal example on [codesandbox](https://codesandbox.io) or similar, I'd be happy to take a look at it!

**Comment by Vincent-Cui** [comment]
Hi @romain130492 have you solved this problem? I got the same problem, it looks like the choropleth-layer will not update after value changed
