### ISSUE TITLE
Strange behaviour when map center set in template.

### ISSUE THREAD

**Issue by aToO57** [vue-leaflet/Vue2Leaflet#614]
### Description

When you set the center directly in `l-map` and have a variable in a tooltip if you move the map and update the tooltip variable the first time it happens, the map is reset to center.

A simple solution is to add a property to the data object, e.g. `mapCenter: [-9336, 10000]`, and then on the map use `:center="mapCenter"`.

#### Live Demo
https://codesandbox.io/s/wierd-bug-iilyo?file=/App.vue

#### Steps to Reproduce

- Move the map (without click on marker)
- Click on the marker

#### Expected Results
The tooltip opens normally (without any map movement)

#### Actual Results
The first click on the marker reset the map position to the center.
Only the first click produce the issue, after is you make the same step (move map -> clic) it's work like expected

### Browsers Affected

- [*] Chrome
- [*] Firefox
   but i think all are affected

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

**Comment by mikeu** [comment]
I discussed this a bit with @aToO57 on the discord. I think the issue is somehow related to the interplay of how Vue watches function with props that are set to hard coded values, as opposed to references to `data` properties (whether or not they are set initially by hard coded values). My guess is that when something triggers a redraw on the map (in this case, opening the tooltip with a newly computed label), the `center` prop gets set to a new copy/instance of the "same" array that is present in the `<l-map :center="[1, 2]"`.

What happens is, changing the tooltip causes some re-rendering to occur, at which point the watch set up by `propsBinder` on `center` calls the custom `setCenter` method, with `newVal` and `oldVal` apparently identical (i.e. both `[1, 2]`, but presumably different instances of arrays, just both containing those two values in that order).

In the `LMap`, `lastSetCenter` is initially null, so inside `setCenter`, `oldCenter` gets set to the _current_ (now moved) map centre, which is different from the "new" hard coded array value used in `newCenter`. Since the new and old values don't match, `setCenter` pans the map to `newCenter`, which is really the older initial value.

Without having tried anything in code, I think the best solution is likely to be simply setting the initial value of `lastSetCenter` to `this.center` instead of `null` in the `LMap`'s data object. I don't see any reason that would ever not make sense. Will try to investigate further before too long.
