### ISSUE TITLE
Toggling between bounds and center & zoom sometimes show invalid views

### ISSUE THREAD

**Issue by tiltec** [vue-leaflet/Vue2Leaflet#617]
### Description

When alternating between using `bounds` or `center` and `zoom` on one `LMap` instance, it sometimes shows invalid views, e.g. whole world or zooming into the middle of the ocean.

My guess is this happens because every props change triggers a watcher that calls `setBounds` or `panTo` on Leaflet. If they are called with `undefined` or in the wrong order, chaos ensues.

#### Live Demo

Click the button in this Codepen:

https://codepen.io/tiltec/pen/poyNJbr

#### Expected Results

Bounds or center/zoom are always respected

#### Actual Results

Erratic zooming behavior

### Browsers Affected

- [x] Chrome
- [x] Firefox

Didn't check those:
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v2.5.12
- Vue2Leaflet: v2.5.2

**Comment by mikeu** [comment]
Thanks for the issue @tiltec , and especially the demo!

I've taken a look and think the problem is actually more related to how Vue2Leaflet caches whether or not it needs to update the map on prop changes—the current logic tends to rely on the assumption that for the most part, you'll pick one way of setting the map view and stick with it.

Will work on getting a fix out soon, hopefully.
