### ISSUE TITLE
How to create markers programatically

### ISSUE THREAD

**Issue by ejohmac** [vue-leaflet/Vue2Leaflet#623]
Hi
Firstly great Vue library.
I've searched through the examples and googled but have still failed to find out how to create circle markers or markers programatically?
So I can create them using the <l-circle-marker> but how do i do it dynamically?

I have tried various attempts of using the ref that is mentioned in your docs to the leaflet API but I still cannot see a marker on my map. For example

this.$refs.myMap.mapObject.circleMarker([54.990303, -8.525841], { color: 'red', fillColor: '#f03', fillOpacity: 0.5, radius: 500 }).addTo(this.$refs.myMap.mapObject);

where the ref to my map is call myMap.

Can you give an example of how to create markers/circle markers dynamically?

Many thanks

**Comment by mikeu** [comment]
Hi @ejohmac !

May I ask what your use case is for needing to be able to do this, instead of using the Vue components provided by vue2-leaflet, such as `<l-circle-marker>`? If you want to use Leaflet in your application directly and do things imperatively instead of declaratively there's nothing wrong with that of course, but then I'm not sure what the point of using Vue and vue2-leaflet is.

If you really do want to do this, I think your best bet will probably be to `import L from "leaflet"` and then call
```js
L.circleMarker([54.990303, -8.525841], { color: 'red', fillColor: '#f03', fillOpacity: 0.5, radius: 500 })
  .addTo(this.$refs.myMap.mapObject);
```

**Comment by mikeu** [comment]
> So I can create them using the but how do i do it dynamically?

Rereading your question the next day @ejohmac , if the more important part of what you're trying to do is to dynamically add circle markers to your vue2-leaflet map, and you don't specifically _require_ to do that programmatically, then the approach I would recommend would be to have an array of marker definitions in your Vue `data` object, use `<l-circle-marker v-for=...` to have one marker on the map for each definition, and then modify that array whenever you need to add or remove markers.

Here's an example of that in action: https://codesandbox.io/s/v2l-dynamic-circle-markers-dmyy3?file=/src/App.vue

**Comment by jjhhsss** [comment]
lololol
