### ISSUE TITLE
Bump version of leaflet in package.json

### ISSUE THREAD

**Issue by mhirsch** [vue-leaflet/Vue2Leaflet#628]
[package.json](https://github.com/vue-leaflet/Vue2Leaflet/blob/b5fb197b56ddac7b2a6921bd5c78037e0fc2a7b2/package.json#L96) refers to leaflet 1.5.7. The latest available in npm is leaflet@1.7.1. I've tested 1.7.1. with vue2-leaflet@2.5.2 and things seem to work in my project. (I have not run the vue2-leaflet tests). Is there any obstacle to running with leaflet@1.7.1?

**Comment by mikeu** [comment]
@mhirsch There shouldn't be any obstacles, so long as the new version of Leaflet didn't make any breaking changes to its API. If you find any issues, please report them here!

Leaflet is kept as a peer dependency, exactly so that you're free to select any 1.x version of Leaflet you'd like (later than the minimum of 1.3.4), without requiring a corresponding re-release of Vue2Leaflet.

**Comment by mhirsch** [comment]
Thank you for your explanation. I haven't run into problems with 1.7.1 so far. The issue that drove my comment was seeing this warning from npm: 

```
npm WARN vue2-leaflet@2.5.2 requires a peer of @types/leaflet@^1.5.7 but none is installed. You must install peer dependencies yourself.
```

I realize now that this is because I haven't installed the typescript definitions for leaflet. Since I'm not working with a typescript project I don't have any need for these. From a bit of googling it doesn't sound like there's a clean way to handle that situation so I guess I'll live with the warning.  Thanks again!

**Comment by mikeu** [comment]
@mhirsch sounds great, glad you're all sorted! I personally like to install the various `@types` libraries to my dev dependencies even in projects that don't use Typescript, because they'll still often let my IDE provide better autocomplete suggestions. But it is a warning and not an error exactly because you can totally continue to ignore it if you prefer that approach!
