### ISSUE TITLE
l-popup fails to open on Safari

### ISSUE THREAD

**Issue by mwargan** [vue-leaflet/Vue2Leaflet#648]
### Description

L-Popup fails to open/trigger properly on Safari 14.0.

Example works fine in Chrome.

#### Live Demo
https://vue2-leaflet.netlify.app/components/LPopup.html#demo <-- see the default example on Safari - fails

#### Expected Results
Opening of popup

#### Actual Results
No result

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
- [x] Safari 14

### Versions
- Leaflet: v1.7.1
- Vue: v2.6.12
- Vue2Leaflet: v2.6.0

I did not have this issue in Leaflet v1.6.0

**Comment by mikeu** [comment]
Hi @mwargan , thank you for the issue report! I saw something very similar recently on the [discord](https://discord.gg/uVZAfUf), and I believe that the problem you are seeing is caused by [an open issue in Leaflet](https://github.com/Leaflet/Leaflet/issues/7255) introduced in 1.7.1. I don't have Safari myself, but as you point out, rolling back your version of Leaflet for now should solve the problem until they get a fix out!
